var http = require("http");
// localhost:5000 (home)
// localhost:5000/pavbhaji (pavbhaji)
// localhost:5000/dhokla (dhokla)
// localhost:5000/panipuri (panipuri)
// localhost:5000/pulav (pulav)
var server = http.createServer(function (request, response) {
  let url = request.url;
  console.log(url);
  response.writeHead(200, { "content-type": "text/html" });
  if (url === "/") {
    response.write( "<html><head><title>Recipes</title></head><body><h1>Recipe name</h1><ul><li>Pav Bhaji</li><li>Dhokla</li><li>Pani Puri</li><li>Pulav</li></ul></body></html>");
  } else if (url === "/pavbhaji") {
    response.write( "<html><head><title>Pav Bhaji Recipe</title></head><body><h1>Pav Bhaji</h1><h2>Ingredients</h2><ul><li>2 large potatoes (boiled, peeled & mashed)</li><li>1 cup cauliflower (chopped)</li><li>1/2 cup green peas</li><li>1 large carrot (chopped)</li><li>1 large onion (finely chopped)</li><li>2 tomatoes (pureed)</li><li>2 tbsp pav bhaji masala</li><li>1 tsp turmeric powder</li><li>2-3 tbsp butter (or oil)</li><li>1 green chilli (optional, chopped)</li><li>Salt to taste</li><li>Fresh coriander (chopped, for garnish)</li><li>Lemon wedges and pav (bread) to serve</li></ul><h2>Method</h2><ol><li>Pressure-cook or boil potatoes, cauliflower, peas, and carrot until soft. Mash roughly and keep aside.</li><li>Heat butter in a pan. Add chopped onion and saute until translucent.</li><li>Add green chilli (if using) and tomato puree. Cook until oil separates.</li><li>Add turmeric, pav bhaji masala and salt. Cook 1-2 minutes.</li><li>Add the mashed vegetables and about 1/2 to 1 cup water. Mix and simmer 8-10 minutes; mash further with a potato masher for a smooth bhaji.</li><li>Adjust seasoning. Add more butter for richness if desired.</li><li>Garnish with chopped coriander. Serve hot with butter-toasted pav, lemon wedges, and chopped onion.</li></ol><h2>Tips</h2><ul><li>For extra flavour, lightly mash some vegetables and keep a few small pieces for texture.</li><li>Roast tomatoes and onions for a deeper taste before adding water.</li><li>Use fresh pav bhaji masala for best aroma.</li></ul></body></html>");
  }
  else if(url==='/dhokla')
  {
    response.write("<html><head><title>Dhokla Recipe</title></head><body><h1>Dhokla</h1><h2>Ingredients</h2><ul><li>1 cup gram flour (besan)</li><li>1/2 cup semolina (rava/sooji)</li><li>1 cup yogurt (curd)</li><li>1 tsp ginger-green chilli paste</li><li>1 tsp sugar</li><li>1 tsp lemon juice</li><li>1 tsp Eno fruit salt (or baking soda)</li><li>Salt to taste</li><li>Water as needed</li></ul><h2>Tempering</h2><ul><li>2 tbsp oil</li><li>1 tsp mustard seeds</li><li>1 tsp sesame seeds</li><li>2 green chillies (slit)</li><li>Few curry leaves</li><li>2 tbsp chopped coriander</li><li>2 tbsp grated coconut (optional, for garnish)</li></ul><h2>Method</h2><ol><li>In a bowl, mix besan, semolina, yogurt, ginger-chilli paste, sugar, salt, lemon juice, and water to form a smooth batter. Rest 10-15 min.</li><li>Just before steaming, add Eno (or soda) and mix gently. Batter should become frothy.</li><li>Pour into a greased steaming plate and steam for 15-20 minutes or until a knife comes out clean. Cool slightly and cut into squares.</li><li>For tempering: Heat oil, add mustard seeds, sesame seeds, green chillies, and curry leaves. Saute a few seconds and pour over dhokla pieces.</li><li>Garnish with coriander and coconut. Serve with green chutney.</li></ol><h2>Tips</h2><ul><li>Do not overmix after adding Eno; otherwise dhokla won't be fluffy.</li><li>If batter is too thick, add a little water to get pouring consistency.</li><li>Steam on medium heat for even cooking.</li></ul></body></html>")
  }
  else if(url==='/panipuri')
  {
    response.write("<html><head><title>Pani Puri Recipe</title></head><body><h1>Pani Puri</h1><h2>Ingredients</h2><ul><li>20-25 puris (ready-made or homemade)</li><li>2 medium potatoes (boiled, peeled & mashed)</li><li>1/2 cup boiled chickpeas or black gram (optional)</li><li>1 medium onion (finely chopped)</li><li>1 tsp roasted cumin powder</li><li>1 tsp chaat masala</li><li>Salt to taste</li></ul><h2>For Pani (Spicy Water)</h2><ul><li>1 cup mint leaves</li><li>1/2 cup coriander leaves</li><li>2-3 green chillies</li><li>1-inch piece ginger</li><li>2 tbsp tamarind pulp</li><li>1 tsp roasted cumin powder</li><li>1 tsp black salt</li><li>Salt to taste</li><li>4 cups chilled water</li></ul><h2>Method</h2><ol><li>Prepare the pani: Blend mint, coriander, green chillies, ginger, and tamarind pulp to a smooth paste. Mix with 4 cups cold water, add spices and salt, and chill in the fridge.</li><li>Prepare stuffing: Mix mashed potatoes, chickpeas, onion, cumin powder, chaat masala, and salt.</li><li>Gently crack the top of each puri to make a hole.</li><li>Stuff with potato mixture and dip into chilled spicy water.</li><li>Serve immediately and enjoy crispy, tangy pani puri.</li></ol><h2>Tips</h2><ul><li>Always serve pani puri immediately; puris get soggy quickly.</li><li>You can also prepare sweet chutney with tamarind and jaggery to balance the spice.</li><li>Adjust chilli and tamarind as per taste.</li></ul></body></html>")

  }
  else if(url==='/pulav')
  {
    response.write("<html><head><title>Pulav Recipe</title></head><body><h1>Vegetable Pulav</h1><h2>Ingredients</h2><ul><li>2 cups basmati rice (washed & soaked 20 min)</li><li>1 large onion (sliced)</li><li>1 tomato (chopped)</li><li>1 cup mixed vegetables (carrot, beans, peas, cauliflower)</li><li>2 green chillies (slit)</li><li>1 tbsp ginger-garlic paste</li><li>2 tbsp oil or ghee</li><li>1 bay leaf</li><li>2-3 cloves</li><li>2-3 green cardamoms</li><li>1-inch cinnamon stick</li><li>1 tsp cumin seeds</li><li>1 tsp garam masala</li><li>4 cups water</li><li>Salt to taste</li><li>Fresh coriander (for garnish)</li></ul><h2>Method</h2><ol><li>Heat oil or ghee in a pot, add bay leaf, cumin, cloves, cardamom, and cinnamon. Fry till fragrant.</li><li>Add sliced onion and saute until golden. Add ginger-garlic paste and saute briefly.</li><li>Add chopped tomato and cook until soft.</li><li>Add mixed vegetables, green chillies, salt, and garam masala. Cook 2-3 minutes.</li><li>Drain soaked rice and add to the pot. Mix gently with spices and vegetables.</li><li>Add 4 cups water, cover, and cook on low flame until rice is soft and fluffy (about 15-20 minutes).</li><li>Garnish with fresh coriander and serve hot with raita or pickle.</li></ol><h2>Tips</h2><ul><li>Soaking rice makes pulav grains fluffy and non-sticky.</li><li>You can add cashews or raisins for a richer taste.</li><li>Use a heavy-bottomed pan or pressure cooker to avoid burning at the bottom.</li></ul></body></html>");
    }   
    response.end();
});
server.listen(5000);
console.log("server started...");
