const http = require("http");
const dish = [
  {
    name: "Paneer Butter Masala",
    weight: "250g",
    price: 120,
    ingredients: ["Paneer", "Butter", "Tomato", "Cream"],
  },
  {
    name: "Chole Bhature",
    weight: "300g",
    price: 100,
    ingredients: ["Chickpeas", "Flour", "Spices", "Oil"],
  },
  {
    name: "Masala Dosa",
    weight: "200g",
    price: 80,
    ingredients: ["Rice", "Lentils", "Potato", "Spices"],
  },
  {
    name: "Biryani",
    weight: "350g",
    price: 150,
    ingredients: ["Rice", "Meat/Vegetables", "Spices", "Yogurt"],
  },
  {
    name: "Samosa",
    weight: "100g",
    price: 30,
    ingredients: ["Flour", "Potato", "Peas", "Spices"],
  },
  {
    name: "Vada Pav",
    weight: "120g",
    price: 25,
    ingredients: ["Potato", "Bread", "Chutney", "Spices"],
  },
  {
    name: "Rajma Chawal",
    weight: "300g",
    price: 90,
    ingredients: ["Kidney Beans", "Rice", "Spices", "Onion"],
  },
  {
    name: "Idli Sambhar",
    weight: "200g",
    price: 70,
    ingredients: ["Rice", "Lentils", "Spices", "Vegetables"],
  },
  {
    name: "Dhokla",
    weight: "150g",
    price: 60,
    ingredients: ["Gram Flour", "Yogurt", "Spices", "Sugar"],
  },
  {
    name: "Pav Bhaji",
    weight: "250g",
    price: 80,
    ingredients: ["Bread", "Vegetables", "Butter", "Spices"],
  },
  {
    name: "Aloo Paratha",
    weight: "200g",
    price: 50,
    ingredients: ["Flour", "Potato", "Spices", "Butter"],
  },
  {
    name: "Gulab Jamun",
    weight: "80g",
    price: 40,
    ingredients: ["Milk Solids", "Sugar Syrup", "Cardamom"],
  },
  {
    name: "Rasgulla",
    weight: "80g",
    price: 40,
    ingredients: ["Chhena", "Sugar Syrup"],
  },
  {
    name: "Jalebi",
    weight: "100g",
    price: 35,
    ingredients: ["Flour", "Sugar Syrup", "Saffron"],
  },
  {
    name: "Kachori",
    weight: "120g",
    price: 30,
    ingredients: ["Flour", "Lentils", "Spices", "Oil"],
  },
  {
    name: "Pani Puri",
    weight: "150g",
    price: 50,
    ingredients: ["Puri", "Tamarind Water", "Potato", "Chickpeas"],
  },
  {
    name: "Sev Puri",
    weight: "120g",
    price: 55,
    ingredients: ["Puri", "Potato", "Sev", "Chutney"],
  },
  {
    name: "Pulao",
    weight: "250g",
    price: 100,
    ingredients: ["Rice", "Vegetables", "Spices", "Ghee"],
  },
  {
    name: "Chicken Curry",
    weight: "300g",
    price: 160,
    ingredients: ["Chicken", "Onion", "Tomato", "Spices"],
  },
  {
    name: "Mutton Curry",
    weight: "300g",
    price: 200,
    ingredients: ["Mutton", "Onion", "Tomato", "Spices"],
  },
  {
    name: "Fish Curry",
    weight: "250g",
    price: 180,
    ingredients: ["Fish", "Coconut Milk", "Spices", "Tamarind"],
  },
  {
    name: "Egg Curry",
    weight: "250g",
    price: 120,
    ingredients: ["Eggs", "Onion", "Tomato", "Spices"],
  },
  {
    name: "Dal Makhani",
    weight: "250g",
    price: 100,
    ingredients: ["Black Lentils", "Butter", "Cream", "Spices"],
  },
  {
    name: "Roti",
    weight: "50g",
    price: 10,
    ingredients: ["Flour", "Water", "Salt"],
  },
  {
    name: "Naan",
    weight: "80g",
    price: 25,
    ingredients: ["Flour", "Yeast", "Yogurt", "Butter"],
  },
  {
    name: "Bhindi Masala",
    weight: "200g",
    price: 80,
    ingredients: ["Okra", "Onion", "Tomato", "Spices"],
  },
  {
    name: "Aloo Gobi",
    weight: "200g",
    price: 80,
    ingredients: ["Potato", "Cauliflower", "Spices", "Oil"],
  },
  {
    name: "Baingan Bharta",
    weight: "200g",
    price: 85,
    ingredients: ["Eggplant", "Onion", "Tomato", "Spices"],
  },
  {
    name: "Palak Paneer",
    weight: "250g",
    price: 110,
    ingredients: ["Spinach", "Paneer", "Cream", "Spices"],
  },
  {
    name: "Kadhi Pakora",
    weight: "250g",
    price: 90,
    ingredients: ["Yogurt", "Gram Flour", "Spices", "Oil"],
  },
  {
    name: "Malai Kofta",
    weight: "250g",
    price: 120,
    ingredients: ["Paneer", "Potato", "Cream", "Spices"],
  },
  {
    name: "Lassi",
    weight: "200g",
    price: 50,
    ingredients: ["Yogurt", "Sugar", "Cardamom"],
  },
  {
    name: "Butter Naan",
    weight: "80g",
    price: 30,
    ingredients: ["Flour", "Yeast", "Butter"],
  },
  {
    name: "Tandoori Chicken",
    weight: "300g",
    price: 180,
    ingredients: ["Chicken", "Yogurt", "Spices", "Lemon"],
  },
  {
    name: "Shahi Paneer",
    weight: "250g",
    price: 130,
    ingredients: ["Paneer", "Cream", "Tomato", "Spices"],
  },
  {
    name: "Kofta Curry",
    weight: "250g",
    price: 120,
    ingredients: ["Paneer/Vegetables", "Gravy", "Spices", "Cream"],
  },
  {
    name: "Paneer Tikka",
    weight: "200g",
    price: 110,
    ingredients: ["Paneer", "Yogurt", "Spices", "Bell Peppers"],
  },
  {
    name: "Methi Thepla",
    weight: "150g",
    price: 50,
    ingredients: ["Fenugreek Leaves", "Flour", "Spices"],
  },
  {
    name: "Fafda",
    weight: "120g",
    price: 40,
    ingredients: ["Gram Flour", "Spices", "Oil"],
  },
  {
    name: "Dabeli",
    weight: "150g",
    price: 60,
    ingredients: ["Potato", "Chutney", "Bread", "Peanuts"],
  },
  {
    name: "Sev Khamani",
    weight: "150g",
    price: 55,
    ingredients: ["Gram Flour", "Sev", "Spices", "Lemon"],
  },
  {
    name: "Misal Pav",
    weight: "200g",
    price: 80,
    ingredients: ["Sprouts", "Spices", "Bread", "Onion"],
  },
  {
    name: "Poha",
    weight: "150g",
    price: 50,
    ingredients: ["Flattened Rice", "Peanuts", "Spices", "Onion"],
  },
  {
    name: "Upma",
    weight: "150g",
    price: 50,
    ingredients: ["Semolina", "Vegetables", "Spices", "Oil"],
  },
  {
    name: "Chana Masala",
    weight: "200g",
    price: 80,
    ingredients: ["Chickpeas", "Onion", "Tomato", "Spices"],
  },
  {
    name: "Kheer",
    weight: "150g",
    price: 60,
    ingredients: ["Rice", "Milk", "Sugar", "Cardamom"],
  },
  {
    name: "Rabri",
    weight: "150g",
    price: 65,
    ingredients: ["Milk", "Sugar", "Saffron", "Nuts"],
  },
  {
    name: "Pongal",
    weight: "200g",
    price: 70,
    ingredients: ["Rice", "Lentils", "Spices", "Ghee"],
  },
  {
    name: "Appam",
    weight: "150g",
    price: 50,
    ingredients: ["Rice", "Coconut Milk", "Yeast"],
  },
  {
    name: "Vermicelli Kheer",
    weight: "150g",
    price: 60,
    ingredients: ["Vermicelli", "Milk", "Sugar", "Cardamom"],
  },
  {
    name: "Gatte ki Sabzi",
    weight: "250g",
    price: 90,
    ingredients: ["Gram Flour Dumplings", "Yogurt", "Spices"],
  },
  {
    name: "Bajra Roti",
    weight: "80g",
    price: 20,
    ingredients: ["Bajra Flour", "Water", "Salt"],
  },
  {
    name: "Makki ki Roti",
    weight: "80g",
    price: 20,
    ingredients: ["Corn Flour", "Water", "Salt"],
  },
  {
    name: "Sarson da Saag",
    weight: "250g",
    price: 100,
    ingredients: ["Mustard Leaves", "Spinach", "Spices", "Butter"],
  },
  {
    name: "Khichdi",
    weight: "250g",
    price: 70,
    ingredients: ["Rice", "Lentils", "Spices", "Ghee"],
  },
  {
    name: "Dum Aloo",
    weight: "200g",
    price: 90,
    ingredients: ["Potato", "Yogurt", "Spices", "Oil"],
  },
  {
    name: "Prawn Curry",
    weight: "250g",
    price: 200,
    ingredients: ["Prawns", "Coconut Milk", "Spices", "Tamarind"],
  },
  {
    name: "Fish Fry",
    weight: "200g",
    price: 180,
    ingredients: ["Fish", "Spices", "Oil", "Lemon"],
  },
  {
    name: "Chicken Biryani",
    weight: "350g",
    price: 180,
    ingredients: ["Rice", "Chicken", "Spices", "Yogurt"],
  },
  {
    name: "Mutton Biryani",
    weight: "350g",
    price: 200,
    ingredients: ["Rice", "Mutton", "Spices", "Yogurt"],
  },
  {
    name: "Veg Biryani",
    weight: "300g",
    price: 150,
    ingredients: ["Rice", "Vegetables", "Spices", "Ghee"],
  },
  {
    name: "Paneer Biryani",
    weight: "300g",
    price: 160,
    ingredients: ["Rice", "Paneer", "Spices", "Ghee"],
  },
  {
    name: "Dal Tadka",
    weight: "250g",
    price: 80,
    ingredients: ["Yellow Lentils", "Onion", "Tomato", "Spices"],
  },
  {
    name: "Mixed Veg Curry",
    weight: "250g",
    price: 90,
    ingredients: ["Vegetables", "Tomato", "Onion", "Spices"],
  },
  {
    name: "Cabbage Sabzi",
    weight: "200g",
    price: 70,
    ingredients: ["Cabbage", "Onion", "Spices", "Oil"],
  },
  {
    name: "Tomato Chutney",
    weight: "100g",
    price: 40,
    ingredients: ["Tomato", "Chili", "Spices"],
  },
  {
    name: "Cucumber Raita",
    weight: "150g",
    price: 50,
    ingredients: ["Cucumber", "Yogurt", "Spices"],
  },
  {
    name: "Mint Chutney",
    weight: "100g",
    price: 45,
    ingredients: ["Mint", "Coriander", "Green Chili", "Lemon"],
  },
  {
    name: "Aloo Tikki",
    weight: "100g",
    price: 30,
    ingredients: ["Potato", "Spices", "Bread Crumbs"],
  },
  {
    name: "Hara Bhara Kabab",
    weight: "120g",
    price: 50,
    ingredients: ["Spinach", "Peas", "Potato", "Spices"],
  },
  {
    name: "Paneer Pakora",
    weight: "150g",
    price: 60,
    ingredients: ["Paneer", "Gram Flour", "Spices", "Oil"],
  },
  {
    name: "Onion Bhaji",
    weight: "100g",
    price: 40,
    ingredients: ["Onion", "Gram Flour", "Spices", "Oil"],
  },
  {
    name: "Corn Chaat",
    weight: "150g",
    price: 50,
    ingredients: ["Corn", "Chutney", "Spices", "Lemon"],
  },
  {
    name: "Veg Cutlet",
    weight: "120g",
    price: 45,
    ingredients: ["Potato", "Vegetables", "Bread Crumbs", "Spices"],
  },
  {
    name: "Momos",
    weight: "150g",
    price: 60,
    ingredients: ["Flour", "Vegetables/Meat", "Spices"],
  },
  {
    name: "Spring Roll",
    weight: "150g",
    price: 55,
    ingredients: ["Flour", "Vegetables", "Spices", "Oil"],
  },
  {
    name: "Dhokla Sandwich",
    weight: "150g",
    price: 50,
    ingredients: ["Gram Flour", "Vegetables", "Chutney"],
  },
  {
    name: "Batata Vada",
    weight: "100g",
    price: 35,
    ingredients: ["Potato", "Gram Flour", "Spices", "Oil"],
  },
  {
    name: "Sev Puri Chat",
    weight: "120g",
    price: 50,
    ingredients: ["Puri", "Potato", "Sev", "Chutney"],
  },
  {
    name: "Bhel Puri",
    weight: "150g",
    price: 50,
    ingredients: ["Puffed Rice", "Vegetables", "Chutney", "Sev"],
  },
  {
    name: "Papdi Chaat",
    weight: "150g",
    price: 55,
    ingredients: ["Papdi", "Potato", "Chutney", "Sev"],
  },
  {
    name: "Aloo Chaat",
    weight: "120g",
    price: 45,
    ingredients: ["Potato", "Chutney", "Spices"],
  },
  {
    name: "Ragda Pattice",
    weight: "150g",
    price: 60,
    ingredients: ["Potato", "Chickpeas", "Chutney", "Spices"],
  },
];
const server = http.createServer((req, res) => {
  res.writeHead(200, { "content-type": "application/json" });
  let url = req.url;

  let output = JSON.stringify(dish);
  res.write(output);
  res.end();
});
let port = 5000;
server.listen(port, () => {
  console.log("server are given response...");
});
